package edu.poc.languageemulatorandroid;

import tratadorEntrada.ATratadorEntrada;
import af.AF;
import android.app.Activity;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.TextView;
import autogeneretadeanduglylanguagethingsdonottouch.ERTextiveis;
import autogeneretadeanduglylanguagethingsdonottouch.SalvavelTextiveis;
import conversor.ConversorAF;
import er.ER;

public class ERActivity extends Salvavel {
	class ERMalformedFileException extends MalformedFileException{
		private static final long serialVersionUID = -4047155531020193617L;//autogenerated
		}
	
	boolean aceito;
	boolean setado;
	ATratadorEntrada te;
	ConversorAF c;
	ER er;
	Resources r;
	boolean existeEr;
	EditText erimputer;
	TextView ertextoexpressao;
	EditText erimputpadrao;
	TextView ertextopadrao;
	TextView ertextosaida;
	Button gera;
	LinearLayout ll;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_er);
		if (savedInstanceState == null) {
			getSupportFragmentManager().beginTransaction()
					.add(R.id.container, new PlaceholderFragment()).commit();
		}
	}
	protected void setaLingua() {
		erimputer.setHint(lingua.expressao);
		erimputpadrao.setHint(lingua.padrao);
		gera.setText(lingua.Gerar);
		ERTextiveis.setaLingua(lingua);
		SalvavelTextiveis.setaExplicacao(lingua.erexplicacao);
		if(setado)ertextosaida.setText(aceito ? lingua.aceito : lingua.recusado);
		super.setaLingua();
	}

	/**
	 * A placeholder fragment containing a simple view.
	 */
	public static class PlaceholderFragment extends FragmentoGeral {

		public PlaceholderFragment() {
		}

		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container,
				Bundle savedInstanceState) {
			View rootView = inflater.inflate(R.layout.fragment_er, container,
					false);
			return ligaFragmentoGeral((ViewGroup) rootView, inflater, container);
		}
	}

	public void novaExpresao(View V){
		String s = erimputer.getText().toString().toLowerCase();
		erimputer.setText("");
		try{er.novaExpressão(s);
			existeEr=true;}
		catch(RuntimeException r){}
		ertextoexpressao.setText(er.toString());
	}
	public void testaPadrao(View V){
		if(!existeEr) return;
		String s = te.removeSimbolos((erimputpadrao.getText())).toLowerCase();
		ertextopadrao.setText(s);
		erimputpadrao.setText("");
		aceito=er.testaExpressão(s);
		setado=true;
		ertextosaida.setText(aceito ? lingua.aceito : lingua.recusado);
	}
	@Override
	public void parse(String s) throws ERMalformedFileException{
		if(s.length()==0) return;
		int n = s.indexOf(' ');
		String s1 = s.substring(0, n);
		if(!s1.equals("er")) throw(new ERMalformedFileException());
		String s2=s.substring(n+1);
		erimputer.setText(s2);
		novaExpresao(null);
	}
	@Override
	public String toString(View V){
		if(!existeEr) return null;
		return new StringBuilder("ER ").append(w).append(' ').append(h).append(' ').append(ertextoexpressao.getText()).toString();
	}
	public void menuGerar(View V){
		if(!existeEr) return;
		gera.setVisibility(View.GONE);
		ll.setVisibility(View.VISIBLE);
	}
	public void retorna(View V){
		ll.setVisibility(View.GONE);
		gera.setVisibility(View.VISIBLE);
	}
	public void gera(View V){
		retorna(V);
		AF af = er.retornaAF();
		arquivo=new ConversorAF().afToAF(af, w, h, false);
		preparaMensageiro(false);
		Intent intent = new Intent(ERActivity.this, AFNLActivity.class);
	    startActivity(intent);
	}
	@Override
	public void criaEspecifico(){
		te=new ATratadorEntrada();
		er=new ER();
		c = new ConversorAF();
		r = getResources();
		existeEr=false;
		menuaberto=true;
		aenviar=false;
		setado=false;
		menuConfirmaAberto=false;
		erimputer = (EditText)findViewById(R.id.erimputer);
		ertextoexpressao = (TextView)findViewById(R.id.ertextoexpressao);
		erimputpadrao = (EditText)findViewById(R.id.erimputpadrao);
		ertextopadrao=(TextView)findViewById(R.id.ertextopadrao);
		ertextosaida=(TextView)findViewById(R.id.ertextosaida);
		gera = (Button) findViewById(R.id.ergera);
		ll=(LinearLayout)findViewById(R.id.ergeraleiaute);
	}
	@Override
	public void someInicial(View v){
		super.someInicial(v);
		ertextoexpressao.setVisibility(View.VISIBLE);
		ertextopadrao.setVisibility(View.VISIBLE);
		findViewById(R.id.linearLayout1).setVisibility(View.VISIBLE);
		findViewById(R.id.ergera).setVisibility(View.VISIBLE);
		ertextosaida.setVisibility(View.VISIBLE);
	}
	@Override
	public Salvavel pegaContexto() {
		return ERActivity.this;
	}
	@Override
	protected void trazOutroATona() {
		// TODO Auto-generated method stub
		
	}
	@Override
	protected void carregaTextiveisEspecifico() {
		ERTextiveis.carregaTextiveis((Activity) pegaContexto());
	}
	@Override
	protected String pegaNomeAtividade() {
		return lingua.ER;
	}

}
