package edu.poc.languageemulatorandroid;

import gr.GR;
import gr.GRDireita;
import gr.GREsquerda;

import java.util.StringTokenizer;

import tratadorEntrada.ATratadorEntrada;
import af.AF;
import android.app.Activity;
import android.content.Intent;
import android.content.res.Resources;
import android.graphics.drawable.Drawable;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import autogeneretadeanduglylanguagethingsdonottouch.GRTextiveis;
import autogeneretadeanduglylanguagethingsdonottouch.SalvavelTextiveis;
import conversor.ConversorAF;

public class GRActivity extends Salvavel{
	public class GRMalformedFileException extends MalformedFileException{
		private static final long serialVersionUID = 625210344756743094L;//autogenerated
	}
	private String s=null;
	boolean existeGR,menuAtivo;
	boolean aceito, setado;
	boolean parseando;
	Resources r =null;
	GR gr=null;
	ATratadorEntrada te=null;
	TextView tvMove=null;
	TextView tvRemove=null;
	TextView tvDireita=null;
	TextView tvEsquerda=null;
	TextView mostraRegras=null;
	TextView entrada=null;
	TextView saida=null;
	Drawable laranja=null;
	Drawable azul=null;
	View menu=null;
	Button gera=null;
	LinearLayout ll=null;
	View azulado=null;
	View clicado=null;
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_gr);
		if (savedInstanceState == null) {
			getSupportFragmentManager().beginTransaction().add(R.id.container, new PlaceholderFragment()).commit();
		}
	}

	/**
	 * A placeholder fragment containing a simple view.
	 */
	public static class PlaceholderFragment extends FragmentoGeral {
		public PlaceholderFragment() {
		}

		@Override
		public View onCreateView(LayoutInflater inflater, ViewGroup container,
				Bundle savedInstanceState) {
			View rootView = inflater.inflate(telaPequena ? R.layout.fragment_grsmall : R.layout.fragment_gr, container,
					false);
			return ligaFragmentoGeral((ViewGroup) rootView, inflater, container);
		}
	}
	@SuppressWarnings("deprecation")
	public void mostraMenu(View v){
		if(menuaberto) return;
		clicado=v;
		s=((Button)v).getText().toString();
		if(existeGR){
			menu.setVisibility(View.VISIBLE);
			menu.setX(v.getX()+v.getWidth()/2+menu.getWidth());
			menu.setY(v.getY()+v.getHeight()*3/2);
			menu.bringToFront();
			menuAtivo=true;
		}
		else{
			int sdk = android.os.Build.VERSION.SDK_INT;
			existeGR=true;
			if(s.equals(lingua.esquerda)) gr=new GREsquerda();
			else gr=new GRDireita();
			if(sdk < android.os.Build.VERSION_CODES.JELLY_BEAN) {
			    v.setBackgroundDrawable(azul);
			} else {
			    v.setBackground(azul);
			}
			azulado = v;
		}
	}
	public void cancela(View v){
		if(menuaberto)return;
		menu.setVisibility(View.GONE);
		menuAtivo=false;
	}
	@SuppressWarnings("deprecation")
	public void confirmaCriacao(View v){
		if(menuaberto)return;
		((View)v.getParent()).setVisibility(View.GONE);
		existeGR=true;
		if(s.equals(lingua.esquerda)) gr=new GREsquerda();
		else gr=new GRDireita();
		mostraRegras.setText("");
		menuAtivo=false;
		int sdk = android.os.Build.VERSION.SDK_INT;
		existeGR=true;
		if(s.equals(lingua.esquerda)) gr=new GREsquerda();
		else gr=new GRDireita();
		if(sdk < android.os.Build.VERSION_CODES.JELLY_BEAN) {
		    clicado.setBackgroundDrawable(azul);
		    azulado.setBackgroundDrawable(laranja);
		} else {
		    clicado.setBackground(azul);
		    azulado.setBackground(laranja);
		}
		azulado = clicado;
	}
	public void insereNovaRegra(View v){
		if(menuaberto && !parseando)return;
		if(!existeGR||menuAtivo) return;
		String parteEsquerda = te.estado(tvEsquerda.getText());
		String parteDireita = te.removeVirgula(te.removeSimbolos(tvDireita.getText()));
		if(parteEsquerda==null||parteEsquerda.equals("")) return;
		if(parteDireita==null||parteDireita.equals("")) parteDireita="";
		gr.novaRegra(parteEsquerda, parteDireita);
		mostraRegras.setText(gr.toString());
	}
	public void removeRegra(View v){
		if(menuaberto)return;
		if(!existeGR||menuAtivo)return;
		int n;
		try{n = Integer.parseInt(tvRemove.getText().toString());
		gr.removeRegra(n);
		mostraRegras.setText(gr.toString());}
		catch(NumberFormatException nfe){}
	}
	public void moveRegra(View v){
		if(menuaberto)return;
		if(!existeGR||menuAtivo)return;
		int n;
		try{n = Integer.parseInt(tvMove.getText().toString());
		gr.moveRegra(n);
		mostraRegras.setText(gr.toString());}
		catch(NumberFormatException nfe){}
	}
	public void testaPadrao(View v){
		if(menuaberto)return;
		if(!existeGR||menuAtivo)return;
		gr.preparaSimulacao();
		aceito=gr.simula(entrada.getText().toString());
		setado=true;
		gr.paraSimulacao();
		saida.setText(aceito ? lingua.aceito : lingua.recusado);
	}
	@SuppressWarnings("deprecation")
	@Override
	public void parse(String s) throws GRMalformedFileException{
		parseando=true;
		int n = s.indexOf(' ');
		String s1 = s.substring(0, n);
		View v;
		if(s1.equals("GRE")){
			existeGR=true;
			gr=new GREsquerda();
			v = GRTextiveis.pegaButaoEsquerda();
		}
		else if(s1.equals("GRD")){
			existeGR=true;
			gr=new GRDireita();
			v = GRTextiveis.pegaButaoDireita();
		}
		else throw(new GRMalformedFileException());
		int sdk = android.os.Build.VERSION.SDK_INT;
		if(sdk < android.os.Build.VERSION_CODES.JELLY_BEAN) {
		    v.setBackgroundDrawable(azul);
		} else {
		    v.setBackground(azul);
		}
		azulado = v;
		StringTokenizer linhas = new StringTokenizer(s.substring(n+1), System.getProperty("line.separator"));
		StringTokenizer st;
		while(linhas.hasMoreTokens()){
			StringBuilder s2 = new StringBuilder();
			st=new StringTokenizer(linhas.nextToken());
			s1=st.nextToken();
			if(!st.nextToken().equals("->"))throw(new GRMalformedFileException());
			while(st.hasMoreTokens()) s2.append(st.nextToken()).append(' ');
			tvEsquerda.setText(s1);
			tvDireita.setText(s2);
			insereNovaRegra(null);
		}
		parseando=false;
	}
	@Override
	public String toString(View V){
		if (!existeGR) return null;
		StringBuilder sb; 
		if(gr.getClass() == GREsquerda.class) sb= new StringBuilder("GRE ");
		else sb= new StringBuilder("GRE ");
		return sb.append(w).append(' ').append(h).append(' ').append(mostraRegras.getText()).toString();
	}
	public void menuGerar(View V){
		if(menuaberto || !existeGR)return;
		gera.setVisibility(View.GONE);
		ll.setVisibility(View.VISIBLE);
	}
	public void retorna(View V){
		if(menuaberto)return;
		ll.setVisibility(View.GONE);
		gera.setVisibility(View.VISIBLE);
	}
	public void gera(View V){
		if(menuaberto)return;
		retorna(V);
		AF af = gr.retornaAF();
		arquivo=new ConversorAF().afToAF(af, w, h, gr.getClass()==GREsquerda.class);
		preparaMensageiro(false);
		Intent intent = new Intent(GRActivity.this, AFNLActivity.class);
	    startActivity(intent);
	}
	protected void setaLingua() {
		GRTextiveis.setaLingua(lingua);
		SalvavelTextiveis.setaExplicacao(lingua.grexplicacao);
		tvEsquerda.setHint(lingua.novaRegra);
		tvDireita.setHint(lingua.novaRegraDireita);
		tvRemove.setHint(lingua.removerRegra);
		tvMove.setHint(lingua.moveRegra);
		entrada.setHint(lingua.padrao);
		gera.setText(lingua.Gerar);
		if(setado)saida.setText(aceito ? lingua.aceito : lingua.recusado);
		super.setaLingua();
	}
	@Override
	public void criaEspecifico(){
		menuaberto=true;
		existeGR=false;
		setado=false;
		menuAtivo=false;
		r=getResources();
		te=new ATratadorEntrada();
		azul=r.getDrawable(R.drawable.fundobotao);
		laranja=r.getDrawable(R.drawable.menuinicialbotao);
		tvRemove=    (TextView) findViewById(R.id.grimputremoveregra);
		tvMove =     (TextView) findViewById(R.id.grimputmoveregra);
		tvDireita=   (TextView) findViewById(R.id.grimputregradireita);
		tvEsquerda=  (TextView) findViewById(R.id.grimputregraesquerda);
		mostraRegras=(TextView) findViewById(R.id.grtextoimprimeregras);;
		entrada=     (TextView) findViewById(R.id.grimputpadrao);;
		saida=       (TextView) findViewById(R.id.grtextoresposta);;
		menu=                   findViewById(R.id.grleiaute);
		gera=		 (Button) 	findViewById(R.id.grgera);
		ll=		 (LinearLayout) findViewById(R.id.grgeraleiaute);
	}
	@Override
	public void someInicial(View v){
		findViewById(R.id.grleiautemestre).setVisibility(View.VISIBLE);
		findViewById(R.id.grgera).setVisibility(View.VISIBLE);
		super.someInicial(v);
	}
	@Override
	public Salvavel pegaContexto() {
		return GRActivity.this;
	}
	@Override
	protected void trazOutroATona() {
		// TODO Auto-generated method stub
		
	}
	@Override
	protected void carregaTextiveisEspecifico() {
		GRTextiveis.carregaTextiveis((Activity)pegaContexto());
	}
	@Override
	protected String pegaNomeAtividade() {
		return lingua.gr;
	}
}
