package autogeneretadeanduglylanguagethingsdonottouch;

import edu.poc.languageemulatorandroid.R;
import lingua.Lingua;
import android.app.Activity;
import android.widget.Button;

public abstract class AFLikeTextiveis{
    private static Button aflikegeragre;
    private static Button aflikegeragrd;
    private static Button aflikegeragrcancela;
    private static Button aflikegeraafd;
    private static Button aflikegeraafn;
    private static Button aflikegeraafnl;
    private static Button aflikegeraafcancela;
    private static Button aflikegeraaf;
    private static Button aflikegeraer;
    private static Button aflikegeragr;
    private static Button aflikegeramealy;
    private static Button aflikegeramoore;
    private static Button aflikegeracancela;
    private static Button aflikesimplifica;
    private static Button aflikegera;
    private static Button aflikeiniciaemul;
    private static Button aflikesimulapasso;
    private static Button aflikesimulatudo;
    private static Button aflikeresetasimul;
    private static Button aflikeparasimul;
    private static Button aflikeokleiaute5cimaesquerda;
    private static Button aflikeremovetransicaocimaesquerda;
    private static Button aflikeeditatransicaocimaesquerda;
    private static Button aflikeapagaestadocimaesquerda;
    private static Button afliketogglainicialcimaesquerda;
    private static Button afliketogglafinalcimaesquerda;
    private static Button aflikecancelaleiaute3cimaesquerda;
    private static Button aflikeokleiaute4baixoesquerda;
    private static Button aflikecancelleiaute4baixoesquerda;
    private static Button aflikecancelleiaute4cimaesquerda;
    private static Button aflikeokleiaute5cimadireita;
    private static Button aflikeremovetransicaocimadireita;
    private static Button aflikeokleiaute5baixodireita;
    private static Button aflikeremovetransicaobaixodireita;
    private static Button aflikeokleiaute5baixoesquerda;
    private static Button aflikeremovetransicaobaixoesquerda;
    private static Button aflikecriatransicaoestadocimadireita;
    private static Button aflikecriatransicaoestadobaixodireita;
    private static Button aflikecancelaleiaute7cimadireita;
    private static Button aflikemoveestadocimadireita;
    private static Button aflikecancelaleiaute2cimadireita;
    private static Button aflikemoveestadobaixodireita;
    private static Button aflikecancelaleiaute2baixodireita;
    private static Button aflikecancelaleiaute7baixodireita;
    private static Button aflikeokleiaute4baixodireita;
    private static Button aflikecancelleiaute4baixodireita;
    private static Button aflikeokleiaute4cimadireita;
    private static Button aflikecancelleiaute4cimadireita;
    private static Button aflikeokleiaute4cimaesquerda;
    private static Button aflikemoveestadocimaesquerda;
    private static Button aflikecancelaleiaute2cimaesquerda;
    private static Button aflikecriatransicaoestadocimaesquerda;
    private static Button aflikecancelaleiaute7cimaesquerda;
    private static Button aflikemoveestadobaixoesquerda;
    private static Button aflikecancelaleiaute2baixoesquerda;
    private static Button aflikecriatransicaoestadobaixoesquerda;
    private static Button aflikecancelaleiaute7baixoesquerda;
    private static Button aflikeeditatransicaobaixodireita;
    private static Button aflikeapagaestadobaixodireita;
    private static Button afliketogglainicialbaixodireita;
    private static Button afliketogglafinalbaixodireita;
    private static Button aflikeeditatransicaocimadireita;
    private static Button aflikeapagaestadocimadireita;
    private static Button afliketogglainicialcimadireita;
    private static Button afliketogglafinalcimadireita;
    private static Button aflikecancelaleiaute3cimadireita;
    private static Button aflikeeditatransicaobaixoesquerda;
    private static Button aflikeapagaestadobaixoesquerda;
    private static Button afliketogglainicialbaixoesquerda;
    private static Button afliketogglafinalbaixoesquerda;
    private static Button aflikecancelaleiaute3baixoesquerda;
    private static Button aflikecancelaleiaute3baixodireita;
	public static void setaTextoInicial(String s) {
		AFLikeTextiveis.afliketogglainicialcimaesquerda.setText(s);
		AFLikeTextiveis.afliketogglainicialbaixoesquerda.setText(s);
		AFLikeTextiveis.afliketogglainicialcimadireita.setText(s);
		AFLikeTextiveis.afliketogglainicialbaixodireita.setText(s);
	}
	public static void setaTextoFinal(String s) {
		AFLikeTextiveis.afliketogglafinalcimaesquerda.setText(s);
		AFLikeTextiveis.afliketogglafinalbaixoesquerda.setText(s);
		AFLikeTextiveis.afliketogglafinalcimadireita.setText(s);
		AFLikeTextiveis.afliketogglafinalbaixodireita.setText(s);
	}
	public static void setaLingua(Lingua l) {
		AFLikeTextiveis.aflikegeragre.setText(l.GRE);
		AFLikeTextiveis.aflikegeragrd.setText(l.GRD);
		AFLikeTextiveis.aflikegeragrcancela.setText(l.cancel);
		AFLikeTextiveis.aflikegeraafd.setText(l.AFD);
		AFLikeTextiveis.aflikegeraafn.setText(l.AFN);
		AFLikeTextiveis.aflikegeraafnl.setText(l.AFNL);
		AFLikeTextiveis.aflikegeraafcancela.setText(l.cancel);
		AFLikeTextiveis.aflikegeraaf.setText(l.AF);
		AFLikeTextiveis.aflikegeraer.setText(l.GR);
		AFLikeTextiveis.aflikegeragr.setText(l.er);
		AFLikeTextiveis.aflikegeramealy.setText(l.MEALY);
		AFLikeTextiveis.aflikegeramoore.setText(l.MOORE);
		AFLikeTextiveis.aflikegeracancela.setText(l.cancel);
		AFLikeTextiveis.aflikesimplifica.setText(l.Simplificar);
		AFLikeTextiveis.aflikegera.setText(l.Gerar);
		AFLikeTextiveis.aflikeiniciaemul.setText(l.emulInit);
		AFLikeTextiveis.aflikesimulapasso.setText(l.passo);
		AFLikeTextiveis.aflikesimulatudo.setText(l.ok);
		AFLikeTextiveis.aflikeresetasimul.setText(l.resetar);
		AFLikeTextiveis.aflikeparasimul.setText(l.emulfim);
		AFLikeTextiveis.aflikeokleiaute5cimaesquerda.setText(l.ok);
		AFLikeTextiveis.aflikeremovetransicaocimaesquerda.setText(l.removeTrans);
		AFLikeTextiveis.aflikeeditatransicaocimaesquerda.setText(l.newTrans);
		AFLikeTextiveis.aflikeapagaestadocimaesquerda.setText(l.statedelete);
		AFLikeTextiveis.aflikecancelaleiaute3cimaesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikeokleiaute4baixoesquerda.setText(l.ok);
		AFLikeTextiveis.aflikecancelleiaute4baixoesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikecancelleiaute4cimaesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikeokleiaute5cimadireita.setText(l.ok);
		AFLikeTextiveis.aflikeremovetransicaocimadireita.setText(l.removeTrans);
		AFLikeTextiveis.aflikeokleiaute5baixodireita.setText(l.ok);
		AFLikeTextiveis.aflikeremovetransicaobaixodireita.setText(l.removeTrans);
		AFLikeTextiveis.aflikeokleiaute5baixoesquerda.setText(l.ok);
		AFLikeTextiveis.aflikeremovetransicaobaixoesquerda.setText(l.removeTrans);
		AFLikeTextiveis.aflikecriatransicaoestadocimadireita.setText(l.newTrans);
		AFLikeTextiveis.aflikecancelaleiaute7cimadireita.setText(l.cancel);
		AFLikeTextiveis.aflikemoveestadocimadireita.setText(l.move);
		AFLikeTextiveis.aflikecancelaleiaute2cimadireita.setText(l.cancel);
		AFLikeTextiveis.aflikemoveestadobaixodireita.setText(l.move);
		AFLikeTextiveis.aflikecancelaleiaute2baixodireita.setText(l.cancel);
		AFLikeTextiveis.aflikecriatransicaoestadobaixodireita.setText(l.newTrans);
		AFLikeTextiveis.aflikecancelaleiaute7baixodireita.setText(l.cancel);
		AFLikeTextiveis.aflikeokleiaute4baixodireita.setText(l.ok);
		AFLikeTextiveis.aflikecancelleiaute4baixodireita.setText(l.cancel);
		AFLikeTextiveis.aflikeokleiaute4cimadireita.setText(l.ok);
		AFLikeTextiveis.aflikecancelleiaute4cimadireita.setText(l.cancel);
		AFLikeTextiveis.aflikeokleiaute4cimaesquerda.setText(l.ok);
		AFLikeTextiveis.aflikemoveestadocimaesquerda.setText(l.move);
		AFLikeTextiveis.aflikecancelaleiaute2cimaesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikecriatransicaoestadocimaesquerda.setText(l.newTrans);
		AFLikeTextiveis.aflikecancelaleiaute7cimaesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikemoveestadobaixoesquerda.setText(l.move);
		AFLikeTextiveis.aflikecancelaleiaute2baixoesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikecriatransicaoestadobaixoesquerda.setText(l.newTrans);
		AFLikeTextiveis.aflikecancelaleiaute7baixoesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikeeditatransicaobaixodireita.setText(l.newTrans);
		AFLikeTextiveis.aflikeapagaestadobaixodireita.setText(l.statedelete);
		AFLikeTextiveis.aflikeeditatransicaocimadireita.setText(l.newTrans);
		AFLikeTextiveis.aflikeapagaestadocimadireita.setText(l.statedelete);
		AFLikeTextiveis.aflikecancelaleiaute3cimadireita.setText(l.cancel);
		AFLikeTextiveis.aflikeeditatransicaobaixoesquerda.setText(l.newTrans);
		AFLikeTextiveis.aflikeapagaestadobaixoesquerda.setText(l.statedelete);
		AFLikeTextiveis.aflikecancelaleiaute3baixoesquerda.setText(l.cancel);
		AFLikeTextiveis.aflikecancelaleiaute3baixodireita.setText(l.cancel);
	}
	public static void carregaTextiveis(Activity c) {
		AFLikeTextiveis.aflikegeragre=(Button) c.findViewById(R.id.aflikegeragre);
		AFLikeTextiveis.aflikegeragrd=(Button) c.findViewById(R.id.aflikegeragrd);
		AFLikeTextiveis.aflikegeragrcancela=(Button) c.findViewById(R.id.aflikegeragrcancela);
		AFLikeTextiveis.aflikegeraafd=(Button) c.findViewById(R.id.aflikegeraafd);
		AFLikeTextiveis.aflikegeraafn=(Button) c.findViewById(R.id.aflikegeraafn);
		AFLikeTextiveis.aflikegeraafnl=(Button) c.findViewById(R.id.aflikegeraafnl);
		AFLikeTextiveis.aflikegeraafcancela=(Button) c.findViewById(R.id.aflikegeraafcancela);
		AFLikeTextiveis.aflikegeraaf=(Button) c.findViewById(R.id.aflikegeraaf);
		AFLikeTextiveis.aflikegeraer=(Button) c.findViewById(R.id.aflikegeraer);
		AFLikeTextiveis.aflikegeragr=(Button) c.findViewById(R.id.aflikegeragr);
		AFLikeTextiveis.aflikegeramealy=(Button) c.findViewById(R.id.aflikegeramealy);
		AFLikeTextiveis.aflikegeramoore=(Button) c.findViewById(R.id.aflikegeramoore);
		AFLikeTextiveis.aflikegeracancela=(Button) c.findViewById(R.id.aflikegeracancela);
		AFLikeTextiveis.aflikesimplifica=(Button) c.findViewById(R.id.aflikesimplifica);
		AFLikeTextiveis.aflikegera=(Button) c.findViewById(R.id.aflikegera);
		AFLikeTextiveis.aflikeiniciaemul=(Button) c.findViewById(R.id.aflikeiniciaemul);
		AFLikeTextiveis.aflikesimulapasso=(Button) c.findViewById(R.id.aflikesimulapasso);
		AFLikeTextiveis.aflikesimulatudo=(Button) c.findViewById(R.id.aflikesimulatudo);
		AFLikeTextiveis.aflikeresetasimul=(Button) c.findViewById(R.id.aflikeresetasimul);
		AFLikeTextiveis.aflikeparasimul=(Button) c.findViewById(R.id.aflikeparasimul);
		AFLikeTextiveis.aflikeokleiaute5cimaesquerda=(Button) c.findViewById(R.id.aflikeokleiaute5cimaesquerda);
		AFLikeTextiveis.aflikeremovetransicaocimaesquerda=(Button) c.findViewById(R.id.aflikeremovetransicaocimaesquerda);
		AFLikeTextiveis.aflikeeditatransicaocimaesquerda=(Button) c.findViewById(R.id.aflikeeditatransicaocimaesquerda);
		AFLikeTextiveis.aflikeapagaestadocimaesquerda=(Button) c.findViewById(R.id.aflikeapagaestadocimaesquerda);
		AFLikeTextiveis.afliketogglainicialcimaesquerda=(Button) c.findViewById(R.id.afliketogglainicialcimaesquerda);
		AFLikeTextiveis.afliketogglafinalcimaesquerda=(Button) c.findViewById(R.id.afliketogglafinalcimaesquerda);
		AFLikeTextiveis.aflikecancelaleiaute3cimaesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute3cimaesquerda);
		AFLikeTextiveis.aflikeokleiaute4baixoesquerda=(Button) c.findViewById(R.id.aflikeokleiaute4baixoesquerda);
		AFLikeTextiveis.aflikecancelleiaute4baixoesquerda=(Button) c.findViewById(R.id.aflikecancelleiaute4baixoesquerda);
		AFLikeTextiveis.aflikecancelleiaute4cimaesquerda=(Button) c.findViewById(R.id.aflikecancelleiaute4cimaesquerda);
		AFLikeTextiveis.aflikeokleiaute5cimadireita=(Button) c.findViewById(R.id.aflikeokleiaute5cimadireita);
		AFLikeTextiveis.aflikeremovetransicaocimadireita=(Button) c.findViewById(R.id.aflikeremovetransicaocimadireita);
		AFLikeTextiveis.aflikeokleiaute5baixodireita=(Button) c.findViewById(R.id.aflikeokleiaute5baixodireita);
		AFLikeTextiveis.aflikeremovetransicaobaixodireita=(Button) c.findViewById(R.id.aflikeremovetransicaobaixodireita);
		AFLikeTextiveis.aflikeokleiaute5baixoesquerda=(Button) c.findViewById(R.id.aflikeokleiaute5baixoesquerda);
		AFLikeTextiveis.aflikeremovetransicaobaixoesquerda=(Button) c.findViewById(R.id.aflikeremovetransicaobaixoesquerda);
		AFLikeTextiveis.aflikecriatransicaoestadocimadireita=(Button) c.findViewById(R.id.aflikecriatransicaoestadocimadireita);
		AFLikeTextiveis.aflikecriatransicaoestadobaixodireita=(Button) c.findViewById(R.id.aflikecriatransicaoestadobaixodireita);
		AFLikeTextiveis.aflikecancelaleiaute7cimadireita=(Button) c.findViewById(R.id.aflikecancelaleiaute7cimadireita);
		AFLikeTextiveis.aflikemoveestadocimadireita=(Button) c.findViewById(R.id.aflikemoveestadocimadireita);
		AFLikeTextiveis.aflikecancelaleiaute2cimadireita=(Button) c.findViewById(R.id.aflikecancelaleiaute2cimadireita);
		AFLikeTextiveis.aflikemoveestadobaixodireita=(Button) c.findViewById(R.id.aflikemoveestadobaixodireita);
		AFLikeTextiveis.aflikecancelaleiaute2baixodireita=(Button) c.findViewById(R.id.aflikecancelaleiaute2baixodireita);
		AFLikeTextiveis.aflikecancelaleiaute7baixodireita=(Button) c.findViewById(R.id.aflikecancelaleiaute7baixodireita);
		AFLikeTextiveis.aflikeokleiaute4baixodireita=(Button) c.findViewById(R.id.aflikeokleiaute4baixodireita);
		AFLikeTextiveis.aflikecancelleiaute4baixodireita=(Button) c.findViewById(R.id.aflikecancelleiaute4baixodireita);
		AFLikeTextiveis.aflikeokleiaute4cimadireita=(Button) c.findViewById(R.id.aflikeokleiaute4cimadireita);
		AFLikeTextiveis.aflikecancelleiaute4cimadireita=(Button) c.findViewById(R.id.aflikecancelleiaute4cimadireita);
		AFLikeTextiveis.aflikeokleiaute4cimaesquerda=(Button) c.findViewById(R.id.aflikeokleiaute4cimaesquerda);
		AFLikeTextiveis.aflikemoveestadocimaesquerda=(Button) c.findViewById(R.id.aflikemoveestadocimaesquerda);
		AFLikeTextiveis.aflikecancelaleiaute2cimaesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute2cimaesquerda);
		AFLikeTextiveis.aflikecriatransicaoestadocimaesquerda=(Button) c.findViewById(R.id.aflikecriatransicaoestadocimaesquerda);
		AFLikeTextiveis.aflikecancelaleiaute7cimaesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute7cimaesquerda);
		AFLikeTextiveis.aflikemoveestadobaixoesquerda=(Button) c.findViewById(R.id.aflikemoveestadobaixoesquerda);
		AFLikeTextiveis.aflikecancelaleiaute2baixoesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute2baixoesquerda);
		AFLikeTextiveis.aflikecriatransicaoestadobaixoesquerda=(Button) c.findViewById(R.id.aflikecriatransicaoestadobaixoesquerda);
		AFLikeTextiveis.aflikecancelaleiaute7baixoesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute7baixoesquerda);
		AFLikeTextiveis.aflikeeditatransicaobaixodireita=(Button) c.findViewById(R.id.aflikeeditatransicaobaixodireita);
		AFLikeTextiveis.aflikeapagaestadobaixodireita=(Button) c.findViewById(R.id.aflikeapagaestadobaixodireita);
		AFLikeTextiveis.afliketogglainicialbaixodireita=(Button) c.findViewById(R.id.afliketogglainicialbaixodireita);
		AFLikeTextiveis.afliketogglafinalbaixodireita=(Button) c.findViewById(R.id.afliketogglafinalbaixodireita);
		AFLikeTextiveis.aflikeeditatransicaocimadireita=(Button) c.findViewById(R.id.aflikeeditatransicaocimadireita);
		AFLikeTextiveis.aflikeapagaestadocimadireita=(Button) c.findViewById(R.id.aflikeapagaestadocimadireita);
		AFLikeTextiveis.afliketogglainicialcimadireita=(Button) c.findViewById(R.id.afliketogglainicialcimadireita);
		AFLikeTextiveis.afliketogglafinalcimadireita=(Button) c.findViewById(R.id.afliketogglafinalcimadireita);
		AFLikeTextiveis.aflikecancelaleiaute3cimadireita=(Button) c.findViewById(R.id.aflikecancelaleiaute3cimadireita);
		AFLikeTextiveis.aflikeeditatransicaobaixoesquerda=(Button) c.findViewById(R.id.aflikeeditatransicaobaixoesquerda);
		AFLikeTextiveis.aflikeapagaestadobaixoesquerda=(Button) c.findViewById(R.id.aflikeapagaestadobaixoesquerda);
		AFLikeTextiveis.afliketogglainicialbaixoesquerda=(Button) c.findViewById(R.id.afliketogglainicialbaixoesquerda);
		AFLikeTextiveis.afliketogglafinalbaixoesquerda=(Button) c.findViewById(R.id.afliketogglafinalbaixoesquerda);
		AFLikeTextiveis.aflikecancelaleiaute3baixoesquerda=(Button) c.findViewById(R.id.aflikecancelaleiaute3baixoesquerda);
		AFLikeTextiveis.aflikecancelaleiaute3baixodireita=(Button) c.findViewById(R.id.aflikecancelaleiaute3baixodireita);	
	}
}
